class Point(x, y)

async fn main() {
    let p = Point(22, 44).share
    # Test that we execute `test(p)` (and hence see its output)
    # before we detect the error here
    test(p.share).await.x += 1 #! RUN ERROR cannot write to shared fields
    print(p).await
}

async fn test(p) -> {
    print("Hi").await #! OUTPUT Hi
    p
}